### ISSUE TITLE
Setup Redux

### ISSUE THREAD

**Issue by mbchoa** [mbchoa/recipeek#12]
### Work Breakdown:
- [x] Setup Redux middlewares
- [x] Create Redux store
- [x] Create Redux actions
- [x] Create Redux reducers
