### ISSUE TITLE
Project Roadmap

### ISSUE THREAD

**Issue by mbchoa** [mbchoa/recipeek#66]
## Feature Ideas
- [ ] Add recipe detail view using `/:ingredient` route
- [ ] Recipe recommendation system
- [ ] Meal planning

---
### UX
- [ ] Add pagination
- [ ] Display nutrition breakdown
- [ ] Add additional info hover tooltip on health labels
- [ ] Add placeholder images on recipes with images that have not yet fully loaded
- [x] Mobile first responsive design
- [x] Remove Bootstrap dependency
- [x] Add loading indicator when searching recipe (#67)

### Node
- [ ] Implement SSR

### Backend
- [ ] Implement user database

### Development Environment
- [ ] Fix Hot Reloading

### Build Scripts
- [x] Remove gulp entirely and use webpack only
  
### DevOps / Infrastructure
- [x] Setup Heroku deployment pipeline
  
- [ ] Setup Docker Compose configuration
- [ ] Setup caching
